name: Workflow

on: [push, pull_request]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew clean test
      - name: Run coverage
        run: ./gradlew jacocoTestCoverageVerification
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: github
          LABEL: 'coverage'
          ICON: 'codecov'
          STATUS: 'ExampleStatus'
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}